// @generated by protobuf-ts 2.11.0 with parameter output_javascript
// @generated from protobuf file "pbf/metrics/api.proto" (package "metrics", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.11.0 with parameter output_javascript
// @generated from protobuf file "pbf/metrics/api.proto" (package "metrics", syntax proto3)
// tslint:disable
import { HistogramO } from "./histogram";
import { HistogramI } from "./histogram";
import { GaugeO } from "./gauge";
import { GaugeI } from "./gauge";
import { CounterO } from "./counter";
import { CounterI } from "./counter";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service metrics.API
 */
export const API = new ServiceType("metrics.API", [
    { name: "Counter", options: {}, I: CounterI, O: CounterO },
    { name: "Gauge", options: {}, I: GaugeI, O: GaugeO },
    { name: "Histogram", options: {}, I: HistogramI, O: HistogramO }
]);
