// @generated by protobuf-ts 2.11.0 with parameter output_javascript
// @generated from protobuf file "pbf/metrics/api.proto" (package "metrics", syntax proto3)
// tslint:disable
/**
 * @generated ServiceType for protobuf service metrics.API
 */
export declare const API: any;
