// @generated by protobuf-ts 2.11.0 with parameter output_javascript
// @generated from protobuf file "pbf/metrics/api.proto" (package "metrics", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import type { HistogramO } from "./histogram";
import type { HistogramI } from "./histogram";
import type { GaugeO } from "./gauge";
import type { GaugeI } from "./gauge";
import type { CounterO } from "./counter";
import type { CounterI } from "./counter";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service metrics.API
 */
export interface IAPIClient {
  /**
   * @generated from protobuf rpc: Counter
   */
  counter(input: CounterI, options?: RpcOptions): UnaryCall<CounterI, CounterO>;
  /**
   * @generated from protobuf rpc: Gauge
   */
  gauge(input: GaugeI, options?: RpcOptions): UnaryCall<GaugeI, GaugeO>;
  /**
   * @generated from protobuf rpc: Histogram
   */
  histogram(
    input: HistogramI,
    options?: RpcOptions,
  ): UnaryCall<HistogramI, HistogramO>;
}
/**
 * @generated from protobuf service metrics.API
 */
export declare class APIClient implements IAPIClient, ServiceInfo {
  private readonly _transport;
  typeName: any;
  methods: any;
  options: any;
  constructor(_transport: RpcTransport);
  /**
   * @generated from protobuf rpc: Counter
   */
  counter(input: CounterI, options?: RpcOptions): UnaryCall<CounterI, CounterO>;
  /**
   * @generated from protobuf rpc: Gauge
   */
  gauge(input: GaugeI, options?: RpcOptions): UnaryCall<GaugeI, GaugeO>;
  /**
   * @generated from protobuf rpc: Histogram
   */
  histogram(
    input: HistogramI,
    options?: RpcOptions,
  ): UnaryCall<HistogramI, HistogramO>;
}
