// @generated by protobuf-ts 2.11.0 with parameter output_javascript
// @generated from protobuf file "pbf/metrics/counter.proto" (package "metrics", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Result } from "./common";
import { Action } from "./common";
/**
 * CounterI is the input for updating counters.
 *
 * @generated from protobuf message metrics.CounterI
 */
export interface CounterI {
  /**
   * @generated from protobuf field: repeated metrics.Action action = 100
   */
  action: Action[];
}
/**
 * CounterO is the output for updating counters.
 *
 * @generated from protobuf message metrics.CounterO
 */
export interface CounterO {
  /**
   * @generated from protobuf field: repeated metrics.Result result = 100
   */
  result: Result[];
}
declare class CounterI$Type extends MessageType<CounterI> {
  constructor();
  create(value?: PartialMessage<CounterI>): CounterI;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: CounterI,
  ): CounterI;
  internalBinaryWrite(
    message: CounterI,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message metrics.CounterI
 */
export declare const CounterI: CounterI$Type;
declare class CounterO$Type extends MessageType<CounterO> {
  constructor();
  create(value?: PartialMessage<CounterO>): CounterO;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: CounterO,
  ): CounterO;
  internalBinaryWrite(
    message: CounterO,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message metrics.CounterO
 */
export declare const CounterO: CounterO$Type;
export {};
