// @generated by protobuf-ts 2.11.0 with parameter output_javascript
// @generated from protobuf file "pbf/metrics/histogram.proto" (package "metrics", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Result } from "./common";
import { Action } from "./common";
// @generated message type with reflection information, may provide speed optimized methods
class HistogramI$Type extends MessageType {
    constructor() {
        super("metrics.HistogramI", [
            { no: 100, name: "action", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Action }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.action = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated metrics.Action action */ 100:
                    message.action.push(Action.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated metrics.Action action = 100; */
        for (let i = 0; i < message.action.length; i++)
            Action.internalBinaryWrite(message.action[i], writer.tag(100, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message metrics.HistogramI
 */
export const HistogramI = new HistogramI$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HistogramO$Type extends MessageType {
    constructor() {
        super("metrics.HistogramO", [
            { no: 100, name: "result", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Result }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.result = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated metrics.Result result */ 100:
                    message.result.push(Result.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated metrics.Result result = 100; */
        for (let i = 0; i < message.result.length; i++)
            Result.internalBinaryWrite(message.result[i], writer.tag(100, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message metrics.HistogramO
 */
export const HistogramO = new HistogramO$Type();
