// @generated by protobuf-ts 2.11.0 with parameter output_javascript
// @generated from protobuf file "pbf/metrics/histogram.proto" (package "metrics", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Result } from "./common";
import { Action } from "./common";
/**
 * HistogramI is the input for updating histograms.
 *
 * @generated from protobuf message metrics.HistogramI
 */
export interface HistogramI {
  /**
   * @generated from protobuf field: repeated metrics.Action action = 100
   */
  action: Action[];
}
/**
 * HistogramO is the output for updating histograms.
 *
 * @generated from protobuf message metrics.HistogramO
 */
export interface HistogramO {
  /**
   * @generated from protobuf field: repeated metrics.Result result = 100
   */
  result: Result[];
}
declare class HistogramI$Type extends MessageType<HistogramI> {
  constructor();
  create(value?: PartialMessage<HistogramI>): HistogramI;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: HistogramI,
  ): HistogramI;
  internalBinaryWrite(
    message: HistogramI,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message metrics.HistogramI
 */
export declare const HistogramI: HistogramI$Type;
declare class HistogramO$Type extends MessageType<HistogramO> {
  constructor();
  create(value?: PartialMessage<HistogramO>): HistogramO;
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: HistogramO,
  ): HistogramO;
  internalBinaryWrite(
    message: HistogramO,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message metrics.HistogramO
 */
export declare const HistogramO: HistogramO$Type;
export {};
